#!/bin/bash
#This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.



echo -e "\nAAAuthorizer By vitforlinux.wordpress.com\n\nPLEASE USE ONE TIME PER FILE"


if [ $# -eq 0 ]
then
	echo "NO file Authorized - Please add file"
else

	for i in "$@"
	do
		file="$i"
		filetype=${i: -3}
		filename=${file%.*}
		filebase="$(basename "$file")"
		filepos="`pwd $file`"/"$filebase"
		chmod +x "`pwd $file`"/"$filebase"

			echo -e "\nAuthorizing\n"
			pwd "$file"
			echo -e "$filebase"
			echo -e "abi <abi/4.0>,\ninclude <tunables/global>" > /tmp/"$USER"-"$filebase"-AAA
			echo -e \""$filepos"\" " flags=(default_allow) {">> /tmp/"$USER"-"$filebase"-AAA
			echo -e "userns,">> /tmp/"$USER"-"$filebase"-AAA
			echo -e "# Authorized by AAAuthorizer\n}">> /tmp/"$USER"-"$filebase"-AAA
			
			sudo mv /tmp/"$USER"-"$filebase"-AAA /etc/apparmor.d/ && sudo systemctl reload apparmor
		

		
	done
fi


